"""
Jove Observatory Systems Database
Source: https://docs.google.com/spreadsheets/d/14ZfH10fP0cilhL2gYtla0TweSc7uQtz3i8fLZWQ5q-U/
"""

JOVE_SYSTEMS = {
    "Aridia": ["Chibi", "Fihrneh", "Hoseen", "Nema", "Defsunun", "Esubara", "Pserz", "Soza", "Nouta", "Huna", "Isid", "Bazadod"],
    "Black Rise": ["Raihbaka", "Onnamon", "Nisuwa", "Immuri", "Aivonen", "Innia", "Hykanima", "Uchomida", "Ikoskio", "Rakapas", "Enaluri", "Teskanen"],
    "The Bleak Lands": ["Hakodan", "Oteleng", "Uusanen", "Komaa", "Saikamon", "Kurniainen", "Anka"],
    "Branch": ["P7Z-R3", "CX-1XF", "Q-NJZ4", "J52-BH", "SVB-RE", "BU-IU4", "I-7JR4", "KMC-WI", "AH-B84", "O-JPKH", "Z-K495", "52G-NZ", "YG-82V", "4DTQ-K", "C-LP3N", "T-Q2DD", "LRWD-B", "M-HU4V", "NEH-CS", "C-VGYO", "2B7A-3", "W-4FA9"],
    "Cache": ["I6-SYN", "LMM7-L", "U-QMOA", "M-CNUD", "NG-M8K", "JZ-B5Y", "0LY-W1", "U93O-A"],
    "Catch": ["G-AOTH", "GE-94X", "IS-R7P", "F9E-KX", "AX-DOT", "B-XJX4", "E3-SDZ", "7LHB-Z", "SNFV-I", "JA-O6J", "25S-6P", "4-07MU", "JWZ2-V", "OGL8-Q", "I-8D0G", "9-8GBA", "EX-0LQ", "F4R2-Q", "L7XS-5", "ZQ-Z3Y"],
    "The Citadel": ["Yashunen", "Kaunokka", "Irjunen", "Sankkasen", "Tama", "Isutaka", "Konola", "Ishomilken", "Hasama", "Onatoh", "Kusomonmon", "Santola", "Uotila", "Laah", "Komo", "Aikoro"],
    "Cloud Ring": ["O-IVNH", "77-KDQ", "6-4V20", "OU-X3P", "8R-RTB", "QA1-BT", "X-M9ON", "G8AD-C", "28O-JY", "XT-R36"],
    "Cobalt Edge": ["L-Z9NB", "HB-5L3", "FV-YEA", "5E-EZC", "X-41DA", "5HN-D6", "E-B957", "Y-RAW3", "87-1PM", "5ED-4E", "E-BYOS", "FV1-RQ", "CHP-76", "DK0-N8", "1GT-MA"],
    "Curse": ["ES-UWY", "Y-K50G", "J7A-UR", "V7D-JD", "K-MGJ7"],
    "Deklein": ["U-TJ7Y", "MZ1E-P", "XCBK-X", "3JN9-Q", "5W3-DG", "33RB-O", "ZOYW-O", "N-TFXK"],
    "Delve": ["Z3V-1W", "HM-XR2", "D-W7F0", "ZXB-VC", "8F-TK3", "IP6V-X", "F-9PXR", "YZ9-F6", "QY6-RK", "KBAK-I", "M-SRKS"],
    "Derelik": ["Sasta", "Juddi", "Yuzier", "Fovihi", "Moh", "Nimambal", "Shamahi", "Abha", "Salashayama", "Asghatil", "Uplingur", "Akhrad", "Ordize", "Agha", "Serad", "Shach", "Bayuka", "Shenela", "Sendaya", "Kuharah", "Faspera", "Ihal", "Shala", "Bekirdod", "Hasateem", "Asabona", "Hahyil"],
    "Detorid": ["S-51XG", "PQRE-W", "9N-0HF", "GR-X26", "D-0UI0", "NB-ALM", "L8-WNE", "GC-LTF", "1KAW-T", "5J4K-9", "L-QQ6P", "XA5-TY", "9-02G0", "0-G8NO", "7-A6XV", "E51-JE", "U-MFTL", "T-0JWP", "TYB-69", "3-LJW3", "P7MI-T", "RZ-PIY", "Z-2Y2Y", "BOZ1-O", "SY-UWN", "I-9GI1", "62O-UE", "4NDT-W"],
    "Devoid": ["Raa", "Dihra", "Hakshma", "Thakala", "Mendori", "Itsyamil", "Arzad", "Sosan", "Roushzar", "Arayar", "Halenan", "Nidebora", "Odin"],
    "Domain": ["Ziriert", "Valmu", "Rimbah", "Faswiba", "Sobenah", "Nomash", "Avair", "Galeh", "Erzoh", "Shuria", "Jambu", "Zaimeth", "Joppaya", "Hutian", "Esteban", "Seiradih", "Hadonoo", "Murzi", "Ziona", "Nifshed", "Cailanar", "Knophtikoo", "Ebtesham", "Fabin", "Ardishapur Prime", "Nadohman", "Sharji", "Yuhelia", "Nakri", "Yeeramoun", "Somouh", "Boranai", "Ebidan", "Ana", "Arbaz", "Ashab", "Afivad"],
    "Esoteria": ["C-PEWN", "R-ARKN", "P9F-ZG", "JAUD-V", "SN9S-N", "G-4H4C", "HHE5-L", "PE-H02", "YRV-MZ", "G-YZUX", "6EK-BV", "F-UVBV", "NIZJ-0", "CR-0E5", "G2-INZ", "IPX-H5", "Q1-R7K", "D-FVI7"],
    "Essence": ["Mesybier", "Charmerout", "Isenan", "Adrel", "Hulmate", "Arant", "Arnon", "Andole", "Vifrevaert", "Haine", "Algogille", "Heydieles"],
    "Etherium Reach": ["CT8K-0", "1PF-BC", "WPV-JN", "3IK-7O", "8KE-YS", "KMH-J1", "KGT3-6", "RO-0PZ", "9P-870", "F69O-M", "IRD-HU", "4-QDIX", "89-JPE"],
    "Everyshore": ["Scuelazyns", "Antollare", "Leremblompes", "Mormoen", "Marosier", "Mya", "Athinard", "Amattens", "Cherore"],
    "Fade": ["X36Y-G", "0-ARFO", "O1Y-ED"],
    "Feythabolis": ["UD-VZW", "X6-J6R", "OXC-UL", "QK-CDG", "2UK4-N", "K-X5AX", "U-BXU9", "6O-XIO", "3-BADZ", "Z-PNIA", "PO-3QW", "P8-BKO", "DUU1-K", "2-F3OE", "CL-J9W", "UB5Z-3", "I9-ZQZ", "ZID-LE"],
    "The Forge": ["Jakanerva", "Obanen", "Ahtulaima", "Mahtista", "Uoyonen", "Nomaa", "Akkio", "Outuni", "Nuken", "Otomainen", "Osaa", "Ohkunen", "Ukkalen", "Akora", "Shihuken"],
    "Fountain": ["I-CUVX", "P5-EFH", "Z9PP-H", "V6-NY1", "7X-02R", "CHA2-Q", "KCT-0A", "JGOW-Y", "IGE-RI", "6F-H3W", "L-1SW8", "15U-JY", "7BX-6F", "HMF-9D", "R3W-XU", "YRNJ-8", "AC2E-3", "Q-XEB3", "SPLE-Y", "UAYL-F", "H-S80W", "A-HZYL", "PXF-RF", "G-UTHL", "87XQ-0", "Z-YN5Y"],
    "Geminate": ["39-DGG", "L-TOFR", "TJM-JJ", "B-F1MI", "4K0N-J", "WH-2EZ", "QKTR-L", "FDZ4-A", "SR-KBB", "BWF-ZZ", "4-CUM5", "K42-IE", "6L78-1", "O2O-2X", "TDE4-H", "LX-ZOJ", "HKYW-T"],
    "Genesis": ["Vecamia", "Sigga", "Ourapheh", "Pashanai", "Malma", "Simela", "Hadji", "Madomi", "New Eden", "Access", "Central Point", "Nasreri", "Tahli", "Sibe", "Hesarid", "Chamja", "Dom-Aphis", "Habu"],
    "Great Wildlands": ["UT-UZB", "B-VIP9", "UNJ-GX", "4M-P1I", "R-ESG0", "DE71-9", "V89M-R", "7Q-8Z2", "ZM-DNR", "HB-1NJ", "N-RAEL", "8DL-CP", "QQ3-YI", "QM-20X", "YUY-LM", "NE-3GR", "Y4-GQV", "TET3-B", "F5-CGW"],
    "Heimatar": ["Frarn", "Abudban", "Bosboger", "Larkugei", "Krilmokenur", "Bogelek", "Otraren", "Rokofur", "Obrolber", "Ameinaka", "Eystur", "Sist"],
    "Immensea": ["CJNF-J", "O7-7UX", "Y19P-1", "NS2L-4", "U9U-TQ", "6-I162", "Y-C4AL", "R-ORB7", "FRTC-5", "AC-7LZ", "Y-FZ5N"],
    "Impass": ["4OIV-X", "GU-9F4", "DDI-B7", "E7VE-V", "01TG-J", "PZMA-E", "Z-N9IP", "DY-40Z", "6E-MOW", "X-0CKQ"],
    "Insmother": ["GK5Z-T", "GDHN-K", "5C-RPA", "L5-UWT", "F3-8X2", "N7-BIY", "1ZF-PJ", "EKPB-3", "KD-KPR", "5-2PQU", "B-II34", "C1G-XC", "HL-VZX", "N-O53U", "V-QXXK", "F39H-1", "XQP-9C", "O-7LAI", "0-VG7A", "EUU-4N", "MOCW-2", "4CJ-AC", "88A-RA", "ZO-4AR", "RD-FWY", "VBPT-T"],
    "Kador": ["Bersyrim", "Rayeret", "Miah", "Asrios", "Salah", "Hikansog", "Ithar", "Jennim", "Ustnia", "Halibai", "Hiremir", "Ardhis", "Chanoun", "Aharalel", "Peyiri", "Oberen", "Ansasos"],
    "The Kalevala Expanse": ["R1O-GN", "J-OAH2", "86L-9F", "JT2I-7", "LE-67X", "BM-VYZ", "EPCD-D", "TA9T-P", "HD-HOZ", "K76A-3", "6FS-CZ", "HPV-RJ", "C3J0-O", "SH6X-F", "BVRQ-O"],
    "Khanid": ["Arzieh", "Gidali", "Reteka", "Hishai", "Parses", "Tzashrah", "Sazre", "Talidal", "Moro", "Ashmarir", "Seshala", "Nahrneder", "Sassecho", "Dimoohan", "Kuhri", "Zahefeus", "Nakis", "Fanathor", "Aurejet", "Firbha"],
    "Kor-Azor": ["Mora", "Annad", "Masanuh", "Nakregde", "Rannoze", "Khabara", "Ami", "Tralasa", "Andrub", "Shaha"],
    "Lonetrek": ["Yoma", "Sotrentaira", "Ajanen", "Kirras", "Ossa", "Ekura", "Tunttaras", "Ruvas", "Hakonen", "Vuorrassi", "Korama", "Isseras", "Rauntaka", "Aivoli", "Tartoken", "Oishami"],
    "Malpais": ["APES-G", "XTVZ-E", "JA-G0T", "IBOX-2", "S5W-1Z", "7T-0QS", "N-YLOE", "NSI-MW", "H-EBQG", "ZOPZ-6", "DAI-SH", "1NZV-7", "NBW-GD", "RUF3-O", "GL6S-2", "Y-XZA7", "PWPY-4", "VVB-QH", "QSCO-D", "HG-YEQ", "POQP-K"],
    "Metropolis": ["Lirerim", "Nakugard", "Egmar", "Hakeri", "Nedegulf", "Aldilur", "Erindur", "Hodrold", "Eygfe", "Erstur", "Fildar", "Jondik", "Asgeir", "Hilfhurmur", "Egbonbet", "Situner", "Arifsdald", "Ardar", "Aset", "Sirekur", "Eszur", "Lasleinur", "Arnstur", "Hjoramold", "Auner", "Erstet", "Agtver", "Atonder"],
    "Molden Heath": ["Hegfunden", "Osvetur", "Hrokkur", "Sakulda", "Hedaleolfarber", "Altbrard", "Illamur", "Varigne", "Orien", "Gulfonodi"],
    "Oasa": ["U9SE-N", "Y-770C", "U-RELP", "IG-4OF", "X-Z4JW", "DGDT-3", "MZLW-9", "X-CYNC", "RJBC-I", "6U-MFQ", "IO-R2S", "3-JG3X", "HO4E-Q", "JXQJ-B", "XKM-DE", "KED-2O"],
    "Omist": ["OKEO-X", "7-8EOE", "Z-7OK1", "L-AS00", "H90-C9", "99-0GS", "X-EHHD", "M9-FIB", "DJK-67", "KR8-27", "C-WPWH", "9MWZ-B"],
    "Outer Passage": ["YQM-P1", "0-4VQL", "KGCF-5", "2WU-XT", "J7X-VN", "QHH-13", "XUPK-Z", "WIO-OL", "TFPT-U", "QFRV-2", "8-AA98", "2ULC-J", "MC4C-H", "4AZV-W", "CNHV-M", "N-I024", "4O-ZRI", "ZZK-VF", "QOK-SX"],
    "Outer Ring": ["C0T-77", "F5FO-U", "JKJ-VJ", "A-5M31", "0D-CHA", "0-WVQS", "T-Z6J2", "CT7-5V"],
    "Paragon Soul": ["O-MCZR", "ARBX-9", "H8-ZTO", "3PPT-9", "LD-2VL", "O-N589", "GQ2S-8"],
    "Period Basis": ["TCAG-3", "08S-39", "E-DOF2", "RYQC-I", "Z-M5A1", "VQE-CN"],
    "Perrigen Falls": ["MTO2-2", "BEG-RL", "MJ-5F9", "LW-YEW", "E-WMT7", "H-29TM", "OP7-BP", "J9A-BH", "A1F-22", "4-1ECP", "0-U2M4", "JZ-UQC", "JPEZ-R", "XU7-CH", "TAL1-3", "PE-SAM", "RY-2FX", "M4-KX5", "SY-OLX", "PFV-ZH", "9-ZA4Z", "O-QKSM", "VWES-Y"],
    "Placid": ["Cumemare", "Dastryns", "Mercomesier", "Evaulon", "Moclinamaud", "Alsavoinon", "Oicx", "Algasienan", "Amoen", "Aubonnie", "Gallusiene", "Pain", "Aulbres"],
    "Providence": ["HP-6Z6", "2V-CS5", "QBL-BV", "GN7-XY", "FSW-3C", "MH9C-S", "I-MGAB", "8P9-BM", "9UY4-H", "QR-K85", "OXIY-V", "D-6WS1", "N-RMSH", "K1Y-5H", "TU-O0T"],
    "Pure Blind": ["UI-8ZE", "RORZ-H", "RZC-16", "S-MDYI", "UC3H-Y", "4-ABS8", "JC-YX8", "12YA-2", "WW-KGD", "R-2R0G", "KQK1-2", "5ZXX-K", "U-INPD"],
    "Querious": ["E-VKJV", "O3L-95", "A3-LOG", "MKD-O8", "A-BO4V", "OGY-6D", "UVHO-F", "8B-SAJ", "ED-L9T", "TV8-HS", "UYU-VV", "Z-UZZN", "RF-CN3", "W6V-VM", "KEJY-U", "3D5K-R"],
    "Scalding Pass": ["U2-28D", "LQ-OAI", "Q-K2T7", "9PX2-F", "H5N-V7", "6-KPAB", "WFFE-4", "K7-LDX", "F2-NXA", "NSBE-L", "X9V-15", "GN-PDU", "WV0D-1", "4E-EZS", "FYD-TO", "V-F6DQ", "LBC-AW", "2-KPW6", "IAK-JW", "JLO-Z3", "Q-NA5H", "1QZ-Y9"],
    "Sinq Laison": ["Augnais", "Iyen-Oursta", "Crielere", "Colelie", "Alles", "Adiere", "Doussivitte", "Balle", "Eglennaert", "Aunia", "Dunraelare", "Lermireve", "Basgerin", "Croleur", "Unel", "Pucherie", "Fluekele", "Gallareue", "Sharuveil", "Bamiette", "Lamadent", "Stegette", "Adrallezoen"],
    "Solitude": ["Anckee", "Toustain", "Ogaria", "Yvelet", "Stoure", "Maire", "Pertnineere", "Odinesyn", "Weraroix", "Aeter"],
    "The Spire": ["OTJ9-E", "GTB-O4", "K-YL9T", "RXA-W1", "H4X-0I", "M-NP5O", "ETO-OT", "C6C-K9", "KPI-OW", "P65-TA", "K-XJJT", "HIK-MC", "E-BFLT", "B9EA-G"],
    "Stain": ["CJF-1P", "6QBH-S", "L6B-0N", "2B-3M4", "O-CT8N", "XFBE-T", "LGL-SD", "JU-UYK", "373Z-7", "UKYS-5", "J-AYLV", "42-UOW", "A-GPTM", "37S-KO", "WEQT-K", "X5O1-L", "TL-T9Z", "B-G1LG", "2IGP-1", "FV-SE8", "WHG2-7", "Y1-UQ2"],
    "Syndicate": ["5-T0PZ", "617I-I", "2G38-I", "ZN0-SR", "6-CZ49", "Poitot", "FD-MLJ", "9U-TTJ", "5-FGQI", "5-VKCN", "KFR-ZE", "DUV-5Y", "57-YRU", "51-5XG", "CIS-7X", "EU0I-T", "0LTQ-C"],
    "Tash-Murkon": ["Paye", "Hilaban", "Rumida", "Mani", "Tew", "Hoona", "Pera", "Saminer", "Phoren", "Pimsu", "Ahrosseas", "Chamume", "Teshkat", "Ivih", "Gyerzen", "Arakor", "Yeder", "Lari", "Abai", "Ahkour", "Remoriu", "Safilbab", "Kerepa", "Adahum"],
    "Tenal": ["A1RR-M", "S-1LIO", "KMV-CQ", "6OYQ-Z", "EOY-BG", "3DR-CR", "PNS7-J", "5-O8B1", "WV-0R2", "SZ6-TA", "7D-PAT", "T-K10W", "ZK-YQ3", "Q1U-IU"],
    "Tenerifis": ["F-ZBO0", "16AM-3", "PEK-8Z", "T-AKQZ", "0P-U0Q", "9-980U", "ZO-P5K", "Y-EQ0C", "NZW-ZO", "MS1-KJ", "JI1-SY", "KW-OAM", "FE-6YQ", "ZD1-Z2", "Y-ORBJ", "WB-AYY", "BW-WJ2", "3L3N-X", "H-HWQR"],
    "Tribute": ["C2X-M5", "NJ4X-S", "WH-JCA", "SH1-6P", "V0DF-2", "F-749O", "S8-NSQ", "XD-TOV", "W-UQA5", "C8VC-S"],
    "Vale of the Silent": ["H-NOU5", "JZV-F4", "1W-0KS", "Z-8Q65", "BR-6XP", "5T-KM3", "MQ-O27", "MGAM-4", "O-LR1H", "LS9B-9", "VI2K-J", "1VK-6B", "XSQ-TF", "7-K5EL", "1N-FJ8", "FS-RFL", "P3EN-E", "S-NJBB", "6WW-28", "Q-R3GP", "0MV-4W", "ZA0L-U"],
    "Venal": ["2PLH-3", "9IPC-E", "EK2-ET", "OJ-CT4", "M2-2V1", "4RX-EE", "AJCJ-1", "9-266Q", "92K-H2", "K3JR-J", "N5Y-4N", "HBD-CC", "0-XIDJ", "N-Q5PW", "Y6-HPG"],
    "Verge Vendor": ["Raneilles", "Scolluzer", "Tierijev", "Arraron", "Merolles", "Channace", "Alenia", "Adallier", "Claulenne"],
    "Wicked Creek": ["3Q-VZA", "HPBE-D", "R0-DMM", "J-RXYN", "U104-3", "JEQG-7", "5NQI-E", "HD-AJ7", "J7-BDX", "8-OZU1", "G9L-LP", "GPD5-0", "JQU-KY", "4-EFLU", "EIH-IU"]
}
